# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Doizer < Formula
  desc ""
  homepage ""
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lvignoli/doizer/releases/download/v0.3.0/doizer_Darwin_x86_64.tar.gz"
      sha256 "4ab20dd78889e3259718f152ba7cf35577c5d88e9669a16855f25fcb1652f50b"

      def install
        bin.install "doizer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lvignoli/doizer/releases/download/v0.3.0/doizer_Darwin_arm64.tar.gz"
      sha256 "224951eee5441deb331a61a8c07ad5d5579567d901f0b55b89ac65a3442b8c09"

      def install
        bin.install "doizer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lvignoli/doizer/releases/download/v0.3.0/doizer_Linux_x86_64.tar.gz"
        sha256 "ccee5683fd0112dea4dfa0a45d3b1b9089411637b70fca036ea7b6cbde5205cb"

        def install
          bin.install "doizer"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lvignoli/doizer/releases/download/v0.3.0/doizer_Linux_arm64.tar.gz"
        sha256 "81e312343ce7118d5d470ee69967e8aee18be4afaaf19df393a3b0997a746e0f"

        def install
          bin.install "doizer"
        end
      end
    end
  end
end
