# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Doizer < Formula
  desc "Add missing DOIs to your bibtex files."
  homepage "https://github.com/lvignoli/doizer"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lvignoli/doizer/releases/download/v0.3.0/doizer_Darwin_x86_64.tar.gz"
      sha256 "6c7ce94ab95126470ae399a90f07836aa6c2454aa90f26bde50de1c16bb8b3d8"

      def install
        bin.install "doizer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lvignoli/doizer/releases/download/v0.3.0/doizer_Darwin_arm64.tar.gz"
      sha256 "699be441e8ee805b3f3ccb9fc4db6734357be4243a036895bcef711ad05724c7"

      def install
        bin.install "doizer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lvignoli/doizer/releases/download/v0.3.0/doizer_Linux_x86_64.tar.gz"
        sha256 "23fe849ea2bb31c6833258d2cb33553ead659758bc7152fe88bf949e7f9e6baf"

        def install
          bin.install "doizer"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/lvignoli/doizer/releases/download/v0.3.0/doizer_Linux_arm64.tar.gz"
        sha256 "9283e3a0b58d6b289aea8159ad0c74a79f3b5786cf4db3ab144218e1ed824a72"

        def install
          bin.install "doizer"
        end
      end
    end
  end
end
